    # src/rust_lib/Cargo.toml

    [package]
    name = "rust_lib"
    version = "0.1.0"
    edition = "2021"

    [lib]
    crate-type = ["cdylib"] # This specifies a C-compatible dynamic library

    [dependencies]
    