    name: QynAuth CI

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    jobs:
      build-and-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10'
              cache: 'poetry'
              install-poetry: false # <-- CRITICAL CHANGE: Disable setup-python's auto-installation of Poetry

          - name: Install Poetry
            run: |
              python -m pip install --upgrade pip
              python -m pip install pipx
              python -m pipx ensurepath
              pipx install poetry
              poetry config virtualenvs.in-project true
            working-directory: src/python_app

          - name: Install Python dependencies
            working-directory: src/python_app
            run: poetry install

          - name: Build Rust project
            working-directory: src/rust_lib
            run: cargo build --release

          - name: Run Python tests
            working-directory: src/python_app
            run: poetry run pytest

          - name: Run Python linting and formatting checks
            working-directory: src/python_app
            run: |
              poetry run black --check .
              poetry run flake8 .
              poetry run isort --check-only .

          - name: Run Python dependency audit
            working-directory: src/python_app
            run: |
              python -m pip install pip-audit
              poetry export -f requirements.txt --output requirements.txt --without-hashes --dev && pip-audit -r requirements.txt || true
            continue-on-error: true
    