name: QynAuth CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.8.2'
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Python dependencies
        working-directory: src/python_app
        run: poetry install --no-root

      - name: Build Rust project
        working-directory: src/rust_lib
        run: cargo build --release

      - name: Run Python tests
        working-directory: src/python_app
        run: poetry run pytest

      - name: Run Python linting and formatting checks
        working-directory: src/python_app
        run: |
          poetry run black .
          poetry run flake8 .
          poetry run isort --check-only .

      - name: Run Python dependency audit
        working-directory: src/python_app
        run: |
          python -m pip install pip-audit
          poetry export -f requirements.txt --output requirements.txt --without-hashes --dev && pip-audit -r requirements.txt || true
        continue-on-error: true
