    name: QynAuth CI

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    jobs:
      build-and-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'
              # cache: 'poetry' # <-- CRITICAL CHANGE: Removed this line

          - name: Install Poetry
            run: |
              curl -sSL https://install.python-poetry.org | python3 -
              echo "$HOME/.poetry/bin" >> $GITHUB_PATH
              poetry config virtualenvs.in-project true
            working-directory: src/python_app

          - name: Install Python dependencies
            working-directory: src/python_app
            run: poetry install --no-root

          - name: Build Rust project
            working-directory: src/rust_lib
            run: cargo build --release

          - name: Run Python tests
            working-directory: src/python_app
            run: poetry run pytest

          - name: Run Python linting and formatting checks
            working-directory: src/python_app
            run: |
              poetry run black --check .
              poetry run flake8 .
              poetry run isort --check-only .

          - name: Run Python dependency audit
            working-directory: src/python_app
            run: |
              python -m pip install pip-audit
              poetry export -f requirements.txt --output requirements.txt --without-hashes --dev && pip-audit -r requirements.txt || true
            continue-on-error: true